### ISSUE TITLE
Flagged as Malware By Anti-Virus

### ISSUE THREAD

**Issue by AnAceCase** [KA9099/CMB-DevRelease#1]
The program is flagged as Malware by Anti-virus Programs, (in this Case Bitdefender) whilst this is likely a false positive, it is a notice
![image](https://user-images.githubusercontent.com/99553516/175699364-c1363122-63d2-46b2-9bee-de3eac3337e4.png)
![image](https://user-images.githubusercontent.com/99553516/175700049-a133d4ed-1fcc-4041-8282-f8db62e172ac.png)

**Comment by KA9099** [comment]
When my friends were testing out the program they got a bunch of warnings from their antimalware programs and windows defender. Understandable since it's a random exe made with launch4j with no signature or anything like that. Here is the [virus total](https://www.virustotal.com/gui/file/e72f24117f4e5f4af03a420d665b34350767b60d49d63e70bc2607453bbae2f9?nocache=1) link. If you search up "BehavesLike.Win32.Dropper.fh launch4j" you can see a bunch of people complaining about that lol.
