### ISSUE TITLE
Not open source

### ISSUE THREAD

**Issue by roxandtol** [KA9099/CMB-DevRelease#2]
When you made the original post, you mentioned your plans to make the program Open Source, but when I was looking on the repo, I only found thte README.md
[
original comment: ](https://www.reddit.com/r/RaceTrackDesigns/comments/q0gtz9/comment/hf7w2sg/?utm_source=share&utm_medium=web2x&context=3)
![imagen](https://user-images.githubusercontent.com/41841903/175793011-552355c8-9f25-4a41-8fdb-20f6dccf050d.png)

**Comment by KA9099** [comment]
Yup. Lots of people were asking for the program and I didn't have the time since then to work on it. So instead of waiting any longer I decided to release the devbuild. It's not open source currently because I need to refactor the code. I don't want people to start forking while I am fundamentally going to change how the program works soon. Once I release the alpha properly it'll go open source. For now this is just a temporary measure to let people enjoy the program while I find the time to work on it.

**Comment by roxandtol** [comment]
Alright, it was mainly so people could work on it and maybe compile for other OSes

**Comment by KA9099** [comment]
For sure, I will do that as soon as I complete the rework of the program.
The current way it's structured is not great so I don't want people to keep
on building on this program when it's about to be completely reworked.
